### ISSUE TITLE
Fine-Tuning LLaMA 2 Models Errors When Saving Merged Model

### ISSUE THREAD

**Issue by slr1997** [ovh/ai-training-examples#92]
When saving models at the last cell:
`model.save_pretrained(output_merged_dir, safe_serialization=True)`
I got this error:

- RuntimeError: 
            Some tensors share memory, this will lead to duplicate memory on disk and potential differences when loading them again: [{'model.layers.11.self_attn.q_proj.weight', 'model.layers.11.mlp.gate_proj.weight', 'model.layers.11.input_layernorm.weight', 'lm_head.weight'}].
            A potential way to correctly save your model is to use `save_model`.
            More information at https://huggingface.co/docs/safetensors/torch_shared_tensors

How to deal with this problem?

**Comment by MathieuBsqt** [comment]
Hi @slr1997 

This issue seems to be resolved in the latest versions of `transformers`. What version are you currently using? 

Can you please try to update your `transformers` installed version with the following commands: 

`pip uninstall transformers`
`pip install git+https://github.com/huggingface/transformers.git` 

By the way, the error message recommends to use `save_model` instead of `save_pretrained`. 
You can try it if you haven't yet, but unfortunately it seems to me that the `model.save_model(output_merged_dir)`  method is not defined for LLaMA.

**Comment by slr1997** [comment]
@MathieuBsqt Thansk for reply!

Unfortunately I tried both reinstall `tranformers` and use `save_model(model, output_merged_dir)` instead but nothing changed. Could you please tell me the version of the packages such as `transformers` and  `safetensors` in your experiments?

**Comment by MathieuBsqt** [comment]
@slr1997 

Strange : / Maybe it comes from the `safetensors` library, here are the main libraries versions I use:  
```
accelerate               0.22.0.dev0
bitsandbytes             0.41.1
huggingface-hub          0.16.4
datasets                 2.13.1
peft                     0.5.0.dev0
safetensors              0.3.1
tokenizers               0.13.3
trl                      0.5.1.dev0
torch                    2.0.1
transformers             4.32.0.dev0
scipy                    1.11.1
```

**Comment by slr1997** [comment]
@MathieuBsqt These are the same as mine. Even though I have cloned some shared tensor this still didn't work. Maybe I should try to use the same dataset as yours.

**Comment by MathieuBsqt** [comment]
This issue has been closed due to inactivity for 30 days. If you believe it is still relevant, please leave a comment below.
